#!/bin/sh

prog=`basename "$0"`
hmdir=`dirname "$0"`

usage () {
	echo "usage: $prog \"create\" <dir>"
	exit 1
}

create () {
	if [ X"$1" = X"" ]; then
		usage
	fi

	if ! [ -d $1 ]; then
		echo -n "creating $1... " && \
			(mkdir $1 || exit) && \
			echo "done."
	fi

	if ! [ -d $1 ]; then
		echo "couldn't make directory, exiting"
		exit 1
	fi

	echo -n "copying halfmoon framework... " && \
		mkdir $1/halfmoon && \
		cp -rp $hmdir/. $1/halfmoon/ && \
		echo "done."

	echo -n "creating skeleton directory structure... " && \
		cp -rp $1/halfmoon/skel/. $1/ && \
		mkdir $1/models && \
		rm -rf $1/halfmoon/.git && \
		echo "done."

	echo -n "creating random encryption key for session storage... "
		RANDKEY=`openssl rand 16 -hex`
		sed -e "s/\"encryption_key\" => \"\"/\"encryption_key\" => \"${RANDKEY}\"/" \
			$1/config/boot.php > $1/config/boot.php.tmp && \
		mv -f $1/config/boot.php.tmp $1/config/boot.php && \
		echo "done."

	echo ""
	echo "   $1:"
	ls -lF $1 | sed 's/^/   /'
	echo ""

	echo "welcome to halfmoon!"
}

case $1 in
"create")
	create $2
	;;
*)
	usage
esac
