#!/bin/sh -e
#
# Copyright (c) 2009-2017 joshua stein <jcs@jcs.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. The name of the author may not be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

GIT_PATH="https://github.com/jcs/halfmoon.git"

prog=`basename "$0"`
hmdir=`dirname "$0"`

usage () {
	echo "usage: $prog create <app name>"
	exit 1
}

create () {
	if [ X"${1}" = X"" ]; then
		usage
	fi

	ADIR=`dirname $1`
	DIR=""
	APP_NAME=""

	# "app> halfmoon create ." -> $ADIR=`pwd`; $APP_NAME=app
	if [ X"${1}" = X"." ]; then
		ADIR=`cd ${1}; pwd`
		APP_NAME=`basename $ADIR`
		ADIR=`dirname $ADIR`

	# "www> halfmoon create app" -> $ADIR=`pwd`; $APP_NAME=app
	elif [ X"$ADIR" = X"." ] ; then
		ADIR=`cd ${ADIR}; pwd`
		APP_NAME=`basename $1`

	# "www> halfmoon create /path/to/app" -> $ADIR='/path/to'; $APP_NAME=app
	else
		APP_NAME=`basename $1`
	fi

	DIR="${ADIR}/${APP_NAME}"

	if ! [ -d $DIR ]; then
		/bin/echo -n "creating $APP_NAME in $ADIR... " && \
			(mkdir $DIR || exit) && \
			echo "done."
	fi

	if ! [ -d $DIR ]; then
		echo "couldn't make directory, exiting"
		exit 1
	fi

	/bin/echo -n "checking out halfmoon from ${GIT_PATH}... " && \
		mkdir $DIR/halfmoon && \
		git clone -q ${GIT_PATH} $DIR/halfmoon && \
		echo "done."

	/bin/echo -n "creating skeleton directory structure... " && \
		cp -rp $DIR/halfmoon/skel/. $DIR/ && \
		mkdir $DIR/models && \
		echo "done."

	/bin/echo -n "creating random encryption key for session storage... "
		RANDKEY=`openssl rand 16 -hex`
		sed -e "s/%%COOKIE_ENCRYPTION_KEY%%/${RANDKEY}/" \
			-e "s/%%APP_NAME%%/${APP_NAME}/g" \
			$DIR/config/boot.php > $DIR/config/boot.php.tmp && \
		mv -f $DIR/config/boot.php.tmp $DIR/config/boot.php && \
		echo "done."

	sed -e "s/%%APP_NAME%%/${APP_NAME}/g" \
		$DIR/views/layouts/application.phtml > \
			$DIR/views/layouts/application.phtml.tmp && \
		mv -f $DIR/views/layouts/application.phtml.tmp \
			$DIR/views/layouts/application.phtml

	echo ""
	echo "   $DIR:"
	ls -lF $DIR | sed 's/^/   /'
	echo ""

	echo "welcome to halfmoon!"
}

case $1 in
"create")
	shift
	create $1 $2
	;;
*)
	usage
esac
