<?php
/*
	html file rendered in exception handler when in the development environment
*/
?>
<html>
<head>
	<title><?php echo h($title) ?></title>
	<style type="text/css">
		body {
			font-family: sans-serif;
		}
		h2, h3, h4 {
			margin: 0;
		}
		div.info {
			background-color: #eee;
			padding: 10px;
			font-family: monospace;
		}
	</style>
</head>
<body>
<h2><?php echo h($title) ?></h2>
<p>
<tt>HALFMOON_ROOT: <?php echo h(HALFMOON_ROOT) ?></tt>
</p>
<p>
<h3>Backtrace</h3>
</p>
<p>
<div class="info">
<?php

if (!is_null($exception) && is_object($exception))
	foreach (\HalfMoon\Rescuer::masked_stack_trace($exception, true) as $line)
		echo $line . "<br />\n";

?>
</div>
</p>
<p>
<h3>Request</h3>
</p>

<?php foreach (array("get", "post") as $a) { ?>
	<p>
	<h4><?php echo strtoupper($a) ?> Parameters</h4>
	</p>
	<p>
	<div class="info">
	<?php if (isset($request->$a)) { ?>
		<?php foreach ((array)$request->$a as $k => $v) { ?>
			<strong><?php echo h(var_export($k, true)) ?></strong>:
				<?php echo h(var_export($v, true)) ?><br />
		<?php } ?>
	<?php } ?>
	</div>
	</p>
<?php } ?>

<p>
<h4>Uploaded Files</h4>
</p>
<p>
<div class="info">
<?php if (isset($_FILES)) { ?>
	<?php foreach ((array)$_FILES as $k => $v) { ?>
		<strong><?php echo h(var_export($k, true)) ?></strong>:
			<?php echo h(var_export($v, true)) ?><br />
	<?php } ?>
<?php } ?>
</div>
</p>

<p>
<h4>Cookies</h4>
</p>
<p>
<div class="info">
<?php if (isset($_COOKIE)) { ?>
	<?php foreach ((array)$_COOKIE as $k => $v) { ?>
		<strong><?php echo h(var_export($k, true)) ?></strong>
		<?php echo ": " . h(var_export($v, true)) ?><br />
	<?php } ?>
<?php } ?>
</div>
</p>

<p>
<h3>Session</h3>
</p>
<p>
<div class="info">
<?php if (isset($_SESSION)) { ?>
	<?php foreach ((array)$_SESSION as $k => $v) { ?>
		<strong><?php echo h(var_export($k, true)) ?></strong>
		<?php echo ": " . h(var_export($v, true)) ?><br />
	<?php } ?>
<?php } ?>
</div>
</p>

</body>
</html>
