<?php
/*
	html file rendered in exception handler when in the development environment
*/
?>
<html>
<head>
	<title><?php echo h($title) ?></title>
	<style type="text/css">
		h2, h3, h4 {
			margin: 0;
		}
		div.info {
			background-color: #eee;
			padding: 10px;
			font-family: monospace;
		}
	</style>
</head>
<body>
<h2><?php echo h($title) ?></h2>
<p>
<tt>HALFMOON_ROOT: <?php echo h(HALFMOON_ROOT) ?></tt>
</p>
<p>
<h3>Backtrace</h3>
</p>
<p>
<div class="info">
<?php

foreach ($exception->getTrace() as $call) {
	if (isset($call["file"])) {
		$fileparts = explode("/", $call["file"]);

		for ($x = 0; $x < count($fileparts); $x++) {
			$fileparts[$x] = h($fileparts[$x]);

			if ($x == count($fileparts) - 1)
				$fileparts[$x] = "<strong>" . $fileparts[$x] . "</strong>";
		}

		?>
		<?php echo join("/", $fileparts); ?><?php
	} else {
		?><?php echo h($call["class"]) ?><?php
	}
	
	?>:<?php echo h(isset($call["line"]) ? $call["line"] : "") ?>
	in
	<strong><?php echo h($call["function"]) ?>()</strong>
	<br />
	<?php
}

?>
</div>
</p>
<p>
<h3>Request</h3>
</p>

<?php foreach (array("get", "post") as $a) { ?>
	<p>
	<h4><?php echo strtoupper($a) ?> Parameters</h4>
	</p>
	<p>
	<div class="info">
	<?php if (isset($this->$a)) { ?>
		<?php foreach ((array)$this->$a as $k => $v) { ?>
			<strong><?php echo h(var_export($k, true)) ?></strong>:
				<?php echo h(var_export($v, true)) ?><br />
		<?php } ?>
	<?php } ?>
	</div>
	</p>
<?php } ?>

<p>
<h4>Uploaded Files</h4>
</p>
<p>
<div class="info">
<?php if (isset($_FILES)) { ?>
	<?php foreach ((array)$_FILES as $k => $v) { ?>
		<strong><?php echo h(var_export($k, true)) ?></strong>:
			<?php echo h(var_export($v, true)) ?><br />
	<?php } ?>
<?php } ?>
</div>
</p>

<p>
<h3>Session</h3>
</p>
<p>
<div class="info">
<?php if (isset($_SESSION)) { ?>
	<?php foreach ((array)$_SESSION as $k => $v) { ?>
		<?php echo h(var_export($k, true) . ": " . var_export($v, true)) ?><br />
	<?php } ?>
<?php } ?>
</div>
</p>
</body>
</html>
