<!doctype html>
<html lang="en">
<head>
	<title>%%APP_NAME%%</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<?php echo $html->stylesheet_link_tag("application"); ?>
	<?php echo $html->javascript_include_tag(array("prototype", "application")); ?>
</head>
<body>
	<?php echo $html->flash_errors(); ?>
	<?php echo $html->flash_notices(); ?>

	<?php echo $content_for_layout; ?>
</body>
</html>
