<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
	"http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<title>Application</title>
	<?php echo $html->stylesheet_link_tag("application"); ?>
	<?php echo $html->javascript_include_tag(array("prototype", "application")); ?>
</head>
<body>
	<?php echo $html->flash_errors(); ?>
	<?php echo $html->flash_notices(); ?>

	<?php echo $content_for_layout; ?>
</body>
</html>
